ROOTDIR 	= .
CFLAGS 		= -std=c++17 -O3
LDFLAGS 	= -lglfw -lvulkan -ldl -lpthread -lX11 -lXxf86vm -lXrandr -lXi
GLOBAL_D	= -DNDEBUG
WAYLAND_D	= -DWAYLAND
X11_D		= -DX11
SHADER_DIR 	= $(ROOTDIR)/shaders
SHADERS		= $(SHADER_DIR)/shader.vert $(SHADER_DIR)/shader.frag
SHADER_ILS	= $(SHADER_DIR)/vert.spv $(SHADER_DIR)/frag.spv

VulkanTest: main.cpp $(SHADERS)
		g++ $(CFLAGS) $(GLOBAL_D) -o VkTestX11 main.cpp $(LDFLAGS)

VkTestX11: main.cpp $(SHADERS)
	g++ $(CFLAGS) $(GLOBAL_D) $(X11_D) -o VkTestX11 main.cpp $(LDFLAGS)

VkTestWayland: main.cpp $(SHADER_ILS)
	g++ $(CFLAGS) $(GLOBAL_D) $(WAYLAND_D) -o VkTestWayland main.cpp $(LDFLAGS) 

wayland-run: VkTestWayland
	./VkTestWayland

main: VulkanTest

wayland: VkTestWayland

x11: VkTestX11

$(SHADER_ILS): $(SHADERS)
	cd $(SHADER_DIR) && bash compile.sh

clean:
	rm -f VulkanTest

.PHONY: test clean